name: node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install  
          cd /var/www/mywebsite/_work/react_node_cicd/react_node_cicd/frontend
          npm install
          npm run build
          cd ..
          pm2 start 0
          pm2 save
          sudo service nginx restart
